import { defineNuxtConfig } from 'nuxt/config'
import type { NuxtConfig } from '@nuxt/schema'
import '@vite-pwa/nuxt'

// During development we generally don't want the PWA service worker to be
// registered or precaching assets — it often serves stale or blocked assets
// which breaks the dev experience. Only enable the PWA module in production.
const isProd = process.env.NODE_ENV === 'production'

export default defineNuxtConfig({
  compatibilityDate: '2025-11-07',
  devtools: { enabled: true },

  // Modules
  modules: [
    '@pinia/nuxt',
    ['nuxt-tiptap-editor', { prefix: 'Tiptap' }],
    '@nuxt/ui',
    ...(isProd ? ['@vite-pwa/nuxt'] : [])
  ],

  // UI configuration
  ui: {
    global: true,
    safelistColors: ['primary']
  },

  colorMode: {
    preference: 'light'
  },

  // PWA configuration for @vite-pwa/nuxt
  // @ts-ignore: pwa config from @vite-pwa/nuxt module
  pwa: {
    // ensure static assets are included in the precache
    includeAssets: ['favicon.ico', 'robots.txt', 'apple-touch-icon.png'],
    registerType: 'autoUpdate',
    manifest: {
      name: 'Modeh',
      short_name: 'Modeh',
      description: 'Your ultimate learning platform',
      theme_color: '#ffffff',
      lang: 'en',
      scope: '/',
      start_url: '/',
      display: 'standalone',
      orientation: 'portrait-primary',
      icons: [
        { src: '/icon-192x192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
        { src: '/icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
        { src: '/icon-192x192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
        { src: '/icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
      ]
    },
    workbox: {
      mode: 'production',
      // Use skipWaiting and clientsClaim for automatic updates
      skipWaiting: true,
      clientsClaim: true,
      // DO NOT use navigateFallback with SSR - index.html is dynamic and generated by server.js
      // Instead, let Nitro/server.js handle all navigation requests
      navigateFallback: null,
      navigateFallbackAllowlist: [],
      globPatterns: ['**/*.{js,css,woff2,png,svg,ico}'],
      globIgnores: ['**/node_modules/**/*', '.nuxt/**/*', '**/*.html', '**/dist/**/*'],
      runtimeCaching: [
        {
          // Navigation requests (HTML pages) should always go to the network first
          // This ensures SSR-rendered content is always fresh
          urlPattern: ({ request }: any) => request.mode === 'navigate',
          handler: 'NetworkFirst',
          options: {
            cacheName: 'pages',
            networkTimeoutSeconds: 10,
            cacheableResponse: { statuses: [0, 200] }
          }
        },
        {
          urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
          handler: 'CacheFirst',
          options: {
            cacheName: 'google-fonts-cache',
            expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 }, // 1 year
            cacheableResponse: { statuses: [0, 200] }
          }
        },
        {
          urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
          handler: 'CacheFirst',
          options: {
            cacheName: 'gstatic-fonts-cache',
            expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 }, // 1 year
            cacheableResponse: { statuses: [0, 200] }
          }
        },
        {
          urlPattern: ({ url }: any) => url.pathname.startsWith('/api/'),
          handler: 'NetworkFirst',
          options: {
            cacheName: 'api-cache',
            cacheableResponse: { statuses: [0, 200] }
          }
        }
      ],
      cleanupOutdatedCaches: true,
      manifestTransforms: [
        (manifestEntries: any) => {
          const manifest = manifestEntries.map((entry: any) => {
            const isJS = entry.url.endsWith('.js');
            const isCSS = entry.url.endsWith('.css');
            
            // Ensure proper revision hashing for cache busting
            if (isJS || isCSS) {
              entry.revision = null;
            }
            return entry;
          });
          return { manifest, warnings: [] };
        }
      ]
    }
  },

  // Vite aliases
  vite: {
    resolve: {
      alias: {
        'tiptap-extension-math-katex': new URL('./shims/tiptap-extension-math-katex.js', import.meta.url).pathname,
        '#tailwind-config': new URL('./tailwind-config/', import.meta.url).pathname,
        '#tailwind-config/theme/colors': new URL('./tailwind-config/theme/colors.js', import.meta.url).pathname,
        '#tailwind-config/theme': new URL('./tailwind-config/theme', import.meta.url).pathname
      }
    }
  },

  // Nitro
  nitro: {},

  // Global CSS
  css: ['katex/dist/katex.min.css'],

  // tiptap module is registered in `modules` with options above

  // PostCSS Configuration
  postcss: {
    plugins: {
      'tailwindcss/nesting': {},
      tailwindcss: {},
      autoprefixer: {},
    }
  },

  // Runtime config (public)
  runtimeConfig: {
    public: {
      apiBase: process.env.NUXT_PUBLIC_API_BASE ?? 'https://admin.modeh.co.ke',
      // Pusher/Echo configuration
      pusherKey: process.env.NUXT_PUBLIC_PUSHER_KEY ?? 'c631b05ce9d7217de73e',
      pusherCluster: process.env.NUXT_PUBLIC_PUSHER_CLUSTER ?? 'ap2',
      wsHost: process.env.NUXT_PUBLIC_WS_HOST ?? 'api-ap2.pusher.com',
      wsPort: process.env.NUXT_PUBLIC_WS_PORT ? parseInt(process.env.NUXT_PUBLIC_WS_PORT, 10) : 443,
      // Use secure WebSocket for Pusher cloud
      wsProtocol: process.env.NUXT_PUBLIC_WS_PROTOCOL ?? 'wss'
    }
  }
})